
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 28 17:33:25 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 8;
  public static final int GRT = 19;
  public static final int NUMCONST = 40;
  public static final int LPAREN = 35;
  public static final int SEMI = 31;
  public static final int CONTINUE = 12;
  public static final int DECR = 16;
  public static final int INCR = 15;
  public static final int LSS = 21;
  public static final int MINUS = 23;
  public static final int RPAREN = 36;
  public static final int AND = 27;
  public static final int RBOX = 38;
  public static final int OR = 28;
  public static final int COMMA = 32;
  public static final int CLASS = 7;
  public static final int DBLARROW = 39;
  public static final int DIV = 25;
  public static final int PLUS = 13;
  public static final int IF = 44;
  public static final int ASSIGN = 17;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 14;
  public static final int GRTE = 20;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int MOD = 26;
  public static final int IDENT = 43;
  public static final int BREAK = 6;
  public static final int VOID = 5;
  public static final int FOREACH = 47;
  public static final int COLON = 30;
  public static final int ELSE = 45;
  public static final int LBRACE = 33;
  public static final int READ = 10;
  public static final int WHILE = 46;
  public static final int CHARCONST = 42;
  public static final int NEQUAL = 18;
  public static final int LSSE = 22;
  public static final int RBRACE = 34;
  public static final int BOOLCONST = 41;
  public static final int EXTENDS = 11;
  public static final int PROG = 2;
  public static final int LBOX = 37;
  public static final int PRINT = 3;
}

